## List of all input

### Testing with one country

In [1]:
import requests
import pandas as pd
resp = requests.get('https://api.ooni.io/api/v1/aggregation'
             f'?probe_cc=MM&test_name=web_connectivity&since=2022-07-01&until=2023-07-01&axis_x=input&axis_y=measurement_start_day')
j = resp.json()
df = pd.json_normalize(j, record_path='result')
df['probe_cc'] = 'MM'
df['measurement_start_day'] = pd.to_datetime(df['measurement_start_day'])
df_summary = df.groupby(['input','probe_cc'], as_index=False).agg(
        ok_count = ('ok_count', 'sum'),
        anomaly_count = ('anomaly_count', 'sum'),
        confirmed_count = ('confirmed_count', 'sum'),
        failure_count = ('failure_count', 'sum'),
        measurement_count = ('measurement_count', 'sum'),
        measurement_first_day = ('measurement_start_day', 'min'), 
        measurement_latest_day = ('measurement_start_day', 'max') 
        )
df_summary['id'] = df_summary['probe_cc'] + '_' + df_summary['input']

In [2]:
print(df_summary.head())

                                          input probe_cc  ok_count  \
0  http://128.31.0.39:9131/tor/server/authority       MM       761
1    http://131.188.40.189/tor/server/authority       MM      1019
2    http://154.35.175.225/tor/server/authority       MM       540
3  http://171.25.193.9:443/tor/server/authority       MM       969
4    http://193.23.244.244/tor/server/authority       MM       925

   anomaly_count  confirmed_count  failure_count  measurement_count  \
0             80                0            260               1101
1             30                0             63               1112
2            450                0             81               1071
3             20                0             68               1057
4             47                0             68               1040

  measurement_first_day measurement_latest_day  \
0            2022-07-01             2023-06-19
1            2022-07-01             2023-06-19
2            2022-07-01             2023-06-19
3            2022-07-01             2023-06-19
4            2022-07-01             2023-06-19

                                                id
0  MM_http://128.31.0.39:9131/tor/server/authority
1    MM_http://131.188.40.189/tor/server/authority
2    MM_http://154.35.175.225/tor/server/authority
3  MM_http://171.25.193.9:443/tor/server/authority
4    MM_http://193.23.244.244/tor/server/authority

### List of all inputs of all countries

In [3]:
import requests
import pandas as pd
# Burma, Cambodia, Hong Kong (China), India, Indonesia, Malaysia, Philippines, Thailand, Vietnam, Timor Leste
cc_list = [
    'MM',
    'KH',
    'HK',
    'IN',
    'ID',
    'MY',
    'PH',
    'TH',
    'VN',
    'TL'
]
def get_webconnectivity(probe_cc):
    resp = requests.get('https://api.ooni.io/api/v1/aggregation'
             f'?probe_cc={probe_cc}&test_name=web_connectivity&since=2022-07-01&until=2023-07-01&axis_x=input&axis_y=measurement_start_day')
    j = resp.json()
    df = pd.json_normalize(j, record_path='result')
    df['probe_cc'] = probe_cc
    df['measurement_start_day'] = pd.to_datetime(df['measurement_start_day'])
    df_summary = df.groupby(['input','probe_cc'], as_index=False).agg(
        ok_count = ('ok_count', 'sum'),
        anomaly_count = ('anomaly_count', 'sum'),
        confirmed_count = ('confirmed_count', 'sum'),
        failure_count = ('failure_count', 'sum'),
        measurement_count = ('measurement_count', 'sum'),
        measurement_first_day = ('measurement_start_day', 'min'), 
        measurement_latest_day = ('measurement_start_day', 'max') 
        )
    df_summary['id'] = df_summary['probe_cc'] + '_' + df_summary['input']
    return df_summary

# Note: as_index=False is to combine the first 2 headers when doing agg

df_list = []
for cc in cc_list:
    df_list.append(pd.DataFrame(get_webconnectivity(cc)))
    
df_inputs_date_all = pd.concat(df_list)

In [4]:
df_inputs_date_all.to_csv('input_list_2023.csv')

In [5]:
print(df_inputs_date_all.head())

                                          input probe_cc  ok_count  \
0  http://128.31.0.39:9131/tor/server/authority       MM       761
1    http://131.188.40.189/tor/server/authority       MM      1019
2    http://154.35.175.225/tor/server/authority       MM       540
3  http://171.25.193.9:443/tor/server/authority       MM       969
4    http://193.23.244.244/tor/server/authority       MM       925

   anomaly_count  confirmed_count  failure_count  measurement_count  \
0             80                0            260               1101
1             30                0             63               1112
2            450                0             81               1071
3             20                0             68               1057
4             47                0             68               1040

  measurement_first_day measurement_latest_day  \
0            2022-07-01             2023-06-19
1            2022-07-01             2023-06-19
2            2022-07-01             2023-06-19
3            2022-07-01             2023-06-19
4            2022-07-01             2023-06-19

                                                id
0  MM_http://128.31.0.39:9131/tor/server/authority
1    MM_http://131.188.40.189/tor/server/authority
2    MM_http://154.35.175.225/tor/server/authority
3  MM_http://171.25.193.9:443/tor/server/authority
4    MM_http://193.23.244.244/tor/server/authority

## List of all input with category code

### Testing with one country

In [6]:
import requests
import pandas as pd
resp = requests.get('https://api.ooni.io/api/v1/aggregation'
             f'?probe_cc=MM&test_name=web_connectivity&since=2022-07-01&until=2023-07-01&axis_x=input&axis_y=category_code')
j = resp.json()
df = pd.json_normalize(j, record_path='result')
df['probe_cc'] = 'MM'
df['id'] = df['probe_cc'] + '_' + df['input']
df_category = df[['input', 'probe_cc', 'category_code', 'id']]

In [7]:
print(df_category.head())

                            input probe_cc category_code  \
0            http://666games.net/       MM          GAME
1              http://abc.go.com/       MM          NEWS
2       http://abpr2.railfan.net/       MM          MMED
3    http://absdfau.blogspot.com/       MM          POLR
4  http://anonymizer.secuser.com/       MM          ANON

                                  id
0            MM_http://666games.net/
1              MM_http://abc.go.com/
2       MM_http://abpr2.railfan.net/
3    MM_http://absdfau.blogspot.com/
4  MM_http://anonymizer.secuser.com/

### Listing all input with category code for all countries

In [8]:
import requests
import pandas as pd
# Burma, Cambodia, Hong Kong (China), India, Indonesia, Malaysia, Philippines, Thailand, Vietnam, Timor Leste
cc_list = [
    'MM',
    'KH',
    'HK',
    'IN',
    'ID',
    'MY',
    'PH',
    'TH',
    'VN',
    'TL'
]
def get_webconnectivity(probe_cc):
    resp = requests.get('https://api.ooni.io/api/v1/aggregation'
             f'?probe_cc={probe_cc}&test_name=web_connectivity&since=2022-07-01&until=2023-07-01&axis_x=input&axis_y=category_code')
    j = resp.json()
    df = pd.json_normalize(j, record_path='result')
    df['probe_cc'] = probe_cc
    df['id'] = df['probe_cc'] + '_' + df['input']
    df_cat = df[['input', 'probe_cc', 'category_code', 'id']]
    return df_cat

df_list = []
for cc in cc_list:
    df_list.append(pd.DataFrame(get_webconnectivity(cc)))
    
df_all_category = pd.concat(df_list)

In [9]:
df_all_category.to_csv('input_list_cat_2023.csv')

In [10]:
print(df_all_category.head())

                            input probe_cc category_code  \
0            http://666games.net/       MM          GAME
1              http://abc.go.com/       MM          NEWS
2       http://abpr2.railfan.net/       MM          MMED
3    http://absdfau.blogspot.com/       MM          POLR
4  http://anonymizer.secuser.com/       MM          ANON

                                  id
0            MM_http://666games.net/
1              MM_http://abc.go.com/
2       MM_http://abpr2.railfan.net/
3    MM_http://absdfau.blogspot.com/
4  MM_http://anonymizer.secuser.com/

In [11]:
len(df_all_category)

21947

In [12]:
print(df_all_category.tail())

                          input probe_cc category_code  \
1642            https://yts.lt/       TL          FILE
1643            https://yts.mx/       TL          FILE
1644         https://z-lib.org/       TL          FILE
1645  https://zh.wikipedia.org/       TL         CULTR
1646           https://zoom.us/       TL          COMT

                                id
1642            TL_https://yts.lt/
1643            TL_https://yts.mx/
1644         TL_https://z-lib.org/
1645  TL_https://zh.wikipedia.org/
1646           TL_https://zoom.us/

## Putting together list of inputs with category code and max, min measurement_start_day

### Testing with one country

In [13]:
df_inputs_MM = df_summary.merge(df_category, on='id', how='left')
df_inputs_MM = df_inputs_MM[['input_x', 
                   'probe_cc_x', 
                   'ok_count', 
                   'anomaly_count', 
                   'confirmed_count', 
                   'failure_count',
                   'measurement_count',
                   'measurement_first_day',
                   'measurement_latest_day',
                   'category_code']].rename(columns = {
                    'input_x' : 'input',
                    'probe_cc_x' : 'probe_cc'
                    })

In [14]:
len(df_inputs_MM)

2669

In [15]:
print(df_inputs_MM.tail())

                                input probe_cc  ok_count  anomaly_count  \
2664               https://z-lib.org/       MM        19              5
2665        https://zh.wikipedia.org/       MM       268             21
2666  https://zincolatt.blogspot.com/       MM       464             14
2667                  https://zoom.us       MM         2              0
2668                 https://zoom.us/       MM       401              1

      confirmed_count  failure_count  measurement_count measurement_first_day  \
2664                0            223                247            2022-10-17
2665                0              3                292            2022-07-01
2666                0              2                480            2022-07-02
2667                0              0                  2            2023-02-09
2668                0              1                403            2022-07-01

     measurement_latest_day category_code
2664             2023-06-29          FILE
2665             2023-06-29         CULTR
2666             2023-06-30          POLR
2667             2023-03-24           NaN
2668             2023-06-30          COMT

### Listing for all countries

In [16]:
df_inputs_all = df_inputs_date_all.merge(df_all_category, on='id', how='left')
df_inputs_all = df_inputs_all[['input_x', 
                   'probe_cc_x', 
                   'ok_count', 
                   'anomaly_count', 
                   'confirmed_count', 
                   'failure_count',
                   'measurement_count',
                   'measurement_first_day',
                   'measurement_latest_day',
                   'category_code',
                   'id']].rename(columns = {
                    'input_x' : 'input',
                    'probe_cc_x' : 'probe_cc'
                    })

In [17]:
print(df_inputs_all.head())

                                          input probe_cc  ok_count  \
0  http://128.31.0.39:9131/tor/server/authority       MM       761
1    http://131.188.40.189/tor/server/authority       MM      1019
2    http://154.35.175.225/tor/server/authority       MM       540
3  http://171.25.193.9:443/tor/server/authority       MM       969
4    http://193.23.244.244/tor/server/authority       MM       925

   anomaly_count  confirmed_count  failure_count  measurement_count  \
0             80                0            260               1101
1             30                0             63               1112
2            450                0             81               1071
3             20                0             68               1057
4             47                0             68               1040

  measurement_first_day measurement_latest_day category_code  \
0            2022-07-01             2023-06-19           NaN
1            2022-07-01             2023-06-19           NaN
2            2022-07-01             2023-06-19           NaN
3            2022-07-01             2023-06-19           NaN
4            2022-07-01             2023-06-19           NaN

                                                id
0  MM_http://128.31.0.39:9131/tor/server/authority
1    MM_http://131.188.40.189/tor/server/authority
2    MM_http://154.35.175.225/tor/server/authority
3  MM_http://171.25.193.9:443/tor/server/authority
4    MM_http://193.23.244.244/tor/server/authority

In [18]:
print(df_inputs_all.tail())

                           input probe_cc  ok_count  anomaly_count  \
27702          https://z-lib.is/       TL         1              0
27703         https://z-lib.org/       TL         0              0
27704  https://zh.wikipedia.org/       TL         1              0
27705  https://zlibrary-asia.se/       TL         1              0
27706           https://zoom.us/       TL         1              1

       confirmed_count  failure_count  measurement_count  \
27702                0              0                  1
27703                0              1                  1
27704                0              0                  1
27705                0              0                  1
27706                0              0                  2

      measurement_first_day measurement_latest_day category_code  \
27702            2023-06-02             2023-06-02           NaN
27703            2023-06-24             2023-06-24          FILE
27704            2023-06-24             2023-06-24         CULTR
27705            2023-06-02             2023-06-02           NaN
27706            2022-08-08             2023-06-21          COMT

                                 id
27702          TL_https://z-lib.is/
27703         TL_https://z-lib.org/
27704  TL_https://zh.wikipedia.org/
27705  TL_https://zlibrary-asia.se/
27706           TL_https://zoom.us/

In [19]:
df_inputs_all.to_csv('input_list_2023.csv')

## List of confirmed blockings

### Testing with one country

In [20]:
import requests
import pandas as pd
resp = requests.get('https://api.ooni.io/api/v1/aggregation'
             f'?probe_cc=MM&test_name=web_connectivity&since=2022-07-01&until=2023-07-01&axis_x=input&axis_y=measurement_start_day')
j = resp.json()
df = pd.json_normalize(j, record_path='result')
df['probe_cc'] = 'MM'
df['measurement_start_day'] = pd.to_datetime(df['measurement_start_day'])
df['confirmed_count'] = pd.to_numeric(df['confirmed_count'])
confirmed_MM = df[df['confirmed_count'] > 0].groupby(['input','probe_cc'], as_index=False).agg(
        blocking_first_day = ('measurement_start_day', 'min'), 
        blocking_latest_day = ('measurement_start_day', 'max')          
        )

In [21]:
len(confirmed_MM)

114

In [22]:
confirmed_MM['id'] = confirmed_MM['probe_cc'] + '_' + confirmed_MM['input']

In [23]:
print(confirmed_MM.head())

                               input probe_cc blocking_first_day  \
0             http://anonymouse.org/       MM         2022-09-25
1             http://aungsanu.com/my       MM         2022-09-25
2       http://burmachannel.website/       MM         2022-12-17
3             http://burmese.dvb.no/       MM         2022-12-17
4  http://join.allpornsitespass.com/       MM         2022-11-09

  blocking_latest_day                                    id
0          2023-05-14             MM_http://anonymouse.org/
1          2023-03-25             MM_http://aungsanu.com/my
2          2023-06-28       MM_http://burmachannel.website/
3          2023-05-14             MM_http://burmese.dvb.no/
4          2023-06-27  MM_http://join.allpornsitespass.com/

In [24]:
import requests
import pandas as pd
# Burma, Cambodia, Hong Kong (China), India, Indonesia, Malaysia, Philippines, Thailand, Vietnam, Timor Leste
cc_list = [
    'MM',
    'KH',
    'HK',
    'IN',
    'ID',
    'MY',
    'PH',
    'TH',
    'VN',
    'TL'
]
def get_webconnectivity(probe_cc):
    resp = requests.get('https://api.ooni.io/api/v1/aggregation'
             f'?probe_cc={probe_cc}&test_name=web_connectivity&since=2022-07-01&until=2023-07-01&axis_x=input&axis_y=measurement_start_day')
    j = resp.json()
    df = pd.json_normalize(j, record_path='result')
    df['probe_cc'] = probe_cc
    df['measurement_start_day'] = pd.to_datetime(df['measurement_start_day'])
    df['confirmed_count'] = pd.to_numeric(df['confirmed_count'])
    confirmed_date = df[df['confirmed_count'] > 0].groupby(['input','probe_cc'], as_index=False).agg(
        blocking_first_day = ('measurement_start_day', 'min'), 
        blocking_latest_day = ('measurement_start_day', 'max')
    )
    confirmed_date['id'] = confirmed_date['probe_cc'] + '_' + confirmed_date['input']
    return confirmed_date

df_list = []
for cc in cc_list:
    df_list.append(pd.DataFrame(get_webconnectivity(cc)))
confirmed_date_all = pd.concat(df_list)

In [25]:
len(confirmed_date_all)

1737

In [26]:
confirmed_date_all.to_csv('confirmed_2023.csv')

In [27]:
print(confirmed_date_all.head(10))

                               input probe_cc blocking_first_day  \
0             http://anonymouse.org/       MM         2022-09-25
1             http://aungsanu.com/my       MM         2022-09-25
2       http://burmachannel.website/       MM         2022-12-17
3             http://burmese.dvb.no/       MM         2022-12-17
4  http://join.allpornsitespass.com/       MM         2022-11-09
5          http://karen.kicnews.org/       MM         2022-08-21
6              http://karennews.org/       MM         2022-07-01
7                http://kicnews.org/       MM         2022-07-01
8     http://medicalsharing.website/       MM         2022-08-21
9                http://mizzima.com/       MM         2022-08-21

  blocking_latest_day                                    id
0          2023-05-14             MM_http://anonymouse.org/
1          2023-03-25             MM_http://aungsanu.com/my
2          2023-06-28       MM_http://burmachannel.website/
3          2023-05-14             MM_http://burmese.dvb.no/
4          2023-06-27  MM_http://join.allpornsitespass.com/
5          2022-12-17          MM_http://karen.kicnews.org/
6          2023-06-28              MM_http://karennews.org/
7          2022-12-17                MM_http://kicnews.org/
8          2023-06-28     MM_http://medicalsharing.website/
9          2023-02-17                MM_http://mizzima.com/

## List of confirmed blockings with probe asn

### Testing with one country

In [28]:
import requests
import pandas as pd
resp = requests.get('https://api.ooni.io/api/v1/aggregation'
             f'?probe_cc=MM&test_name=web_connectivity&since=2022-07-01&until=2023-07-01&axis_x=input&axis_y=probe_asn')
j = resp.json()
df = pd.json_normalize(j, record_path='result')
df['probe_cc'] = 'MM'
df['confirmed_count'] = df['confirmed_count'].astype(int)
df['probe_asn'] = df['probe_asn'].astype(str)
confirmed_asn_MM = df[df['confirmed_count'] > 0][['input','probe_asn', 'probe_cc']]
confirmed_asn_MM = confirmed_asn_MM.pivot_table(index=['input', 'probe_cc'], values='probe_asn',
                                                aggfunc=lambda x: ', '.join(set(x))).reset_index().rename(columns = {
                                                'probe_asn' : 'probe_asn_blocking'})
confirmed_asn_MM['id'] = confirmed_asn_MM['probe_cc'] + '_' + confirmed_asn_MM['input']

In [29]:
display(confirmed_asn_MM.head())

,input,probe_cc,probe_asn_blocking,id
0,http://anonymouse.org/,MM,133385,MM_http://anonymouse.org/
1,http://aungsanu.com/my,MM,"133385, 138168",MM_http://aungsanu.com/my
2,http://burmachannel.website/,MM,"138168, 133385, 136780",MM_http://burmachannel.website/
3,http://burmese.dvb.no/,MM,133385,MM_http://burmese.dvb.no/
4,http://join.allpornsitespass.com/,MM,"134840, 136780",MM_http://join.allpornsitespass.com/

### Doing it for all countries

In [30]:
import requests
import pandas as pd
# Burma, Cambodia, Hong Kong (China), India, Indonesia, Malaysia, Philippines, Thailand, Vietnam, Timor Leste
cc_list = [
    'MM',
    'KH',
    'HK',
    'IN',
    'ID',
    'MY',
    'PH',
    'TH',
    'VN',
    'TL'
]
def get_webconnectivity(probe_cc):
    resp = requests.get('https://api.ooni.io/api/v1/aggregation'
             f'?probe_cc={probe_cc}&test_name=web_connectivity&since=2022-07-01&until=2023-07-01&axis_x=input&axis_y=probe_asn')
    j = resp.json()
    df = pd.json_normalize(j, record_path='result')
    df['probe_cc'] = probe_cc
    df['confirmed_count'] = df['confirmed_count'].astype(int)
    df['probe_asn'] = df['probe_asn'].astype(str)
    confirmed_asn = df[df['confirmed_count'] > 0][['input','probe_asn', 'probe_cc']]
    confirmed_asn = confirmed_asn.pivot_table(index=['input', 'probe_cc'], values='probe_asn',
                                                aggfunc=lambda x: ', '.join(set(x))).reset_index().rename(columns = {
                                                'probe_asn' : 'probe_asn_blocking'})
    confirmed_asn['id'] = confirmed_asn['probe_cc'] + '_' + confirmed_asn['input']
    return confirmed_asn

df_list = []
for cc in cc_list:
    df_list.append(pd.DataFrame(get_webconnectivity(cc)))
confirmed_asn_all = pd.concat(df_list)

In [31]:
display(confirmed_asn_all.head(10))

,input,probe_cc,probe_asn_blocking,id
0,http://anonymouse.org/,MM,133385,MM_http://anonymouse.org/
1,http://aungsanu.com/my,MM,"133385, 138168",MM_http://aungsanu.com/my
2,http://burmachannel.website/,MM,"138168, 133385, 136780",MM_http://burmachannel.website/
3,http://burmese.dvb.no/,MM,133385,MM_http://burmese.dvb.no/
4,http://join.allpornsitespass.com/,MM,"134840, 136780",MM_http://join.allpornsitespass.com/
5,http://karen.kicnews.org/,MM,"134840, 133385",MM_http://karen.kicnews.org/
6,http://karennews.org/,MM,"134840, 133385, 136780",MM_http://karennews.org/
7,http://kicnews.org/,MM,"134840, 133385",MM_http://kicnews.org/
8,http://medicalsharing.website/,MM,"133385, 136780",MM_http://medicalsharing.website/
9,http://mizzima.com/,MM,133385,MM_http://mizzima.com/

In [32]:
display(confirmed_asn_all.tail(10))

,input,probe_cc,probe_asn_blocking,id
37,http://www.xvideos.com/,VN,7552,VN_http://www.xvideos.com/
38,http://www.youporn.com/,VN,7552,VN_http://www.youporn.com/
39,http://xinloiong.jonathanlondon.net/,VN,7552,VN_http://xinloiong.jonathanlondon.net/
40,https://bi.org/,VN,24088,VN_https://bi.org/
41,https://hanhtinhtitanic.org/,VN,"45899, 45903",VN_https://hanhtinhtitanic.org/
42,https://occupystreams.org/,VN,18403,VN_https://occupystreams.org/
43,https://www.giaitriluke.com/,VN,7552,VN_https://www.giaitriluke.com/
44,https://www.haaretz.com/,VN,131429,VN_https://www.haaretz.com/
45,https://www.haaretz.com/life/five-films-you-ha...,VN,131429,VN_https://www.haaretz.com/life/five-films-you...
46,https://www.xaluan.com/,VN,7552,VN_https://www.xaluan.com/

In [33]:
len(confirmed_asn_all)

1737

## Putting together all input with blocking information

In [34]:
confirmed_all = confirmed_date_all.merge(confirmed_asn_all, on='id', how='inner')
confirmed_all = confirmed_all[['input_x', 
                        'probe_cc_x', 
                        'blocking_first_day',
                        'blocking_latest_day',
                        'probe_asn_blocking',
                        'id']].rename(columns = {
                        'input_x' : 'input',
                        'probe_cc_x' : 'probe_cc'
                        })

In [35]:
display(confirmed_all.head())

,input,probe_cc,blocking_first_day,blocking_latest_day,probe_asn_blocking,id
0,http://anonymouse.org/,MM,2022-09-25,2023-05-14,133385,MM_http://anonymouse.org/
1,http://aungsanu.com/my,MM,2022-09-25,2023-03-25,"133385, 138168",MM_http://aungsanu.com/my
2,http://burmachannel.website/,MM,2022-12-17,2023-06-28,"138168, 133385, 136780",MM_http://burmachannel.website/
3,http://burmese.dvb.no/,MM,2022-12-17,2023-05-14,133385,MM_http://burmese.dvb.no/
4,http://join.allpornsitespass.com/,MM,2022-11-09,2023-06-27,"134840, 136780",MM_http://join.allpornsitespass.com/

In [36]:
df_inputs_blocking_all = df_inputs_all.merge(confirmed_all, on='id', how='left')
df_inputs_blocking_all = df_inputs_blocking_all[['input_x', 
                        'probe_cc_x', 
                        'ok_count', 
                        'anomaly_count', 
                        'confirmed_count', 
                        'failure_count',
                        'measurement_count',
                        'measurement_first_day',
                        'measurement_latest_day',
                        'category_code',
                        'blocking_first_day',
                        'blocking_latest_day',
                        'probe_asn_blocking',
                        'id']].rename(columns = {
                        'input_x' : 'input',
                        'probe_cc_x' : 'probe_cc'
                        })

In [37]:
import numpy as np
df_inputs_blocking_all['is_confirmed_ooni'] = np.where(df_inputs_blocking_all['confirmed_count'] > 0, True, False)

In [38]:
df_inputs_blocking_all['anomaly_rate'] = (df_inputs_blocking_all['confirmed_count'] + df_inputs_blocking_all['anomaly_count']) / df_inputs_blocking_all['measurement_count']

In [39]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

from datetime import datetime, timedelta
from dateutil.parser import parse as parse_date
from urllib.parse import urlencode, quote, urlparse

from tqdm import tqdm
tqdm.pandas()

def parse_domain(url):
    try:
        return urlparse(url).netloc
    except:
        print(f'invalid url {url}')
        return ''
df_inputs_blocking_all['domain'] = df_inputs_blocking_all['input'].progress_apply(parse_domain)

100%|█████████████████████████████████| 27707/27707 [00:00<00:00, 138497.82it/s]

In [40]:
df_inputs_blocking_all = df_inputs_blocking_all[['input', 
                        'ok_count', 
                        'anomaly_count', 
                        'confirmed_count', 
                        'failure_count',
                        'measurement_count',
                        'is_confirmed_ooni',
                        'anomaly_rate',
                        'probe_cc',
                        'category_code',
                        'domain',
                        'measurement_first_day',
                        'measurement_latest_day',
                        'blocking_first_day',
                        'blocking_latest_day',
                        'probe_asn_blocking',
                        'id']]

In [41]:
display(df_inputs_blocking_all.head(20))

,input,ok_count,anomaly_count,confirmed_count,failure_count,measurement_count,is_confirmed,anomaly_rate,probe_cc,category_code,domain,measurement_first_day,measurement_latest_day,blocking_first_day,blocking_latest_day,probe_asn_blocking,id
0,http://128.31.0.39:9131/tor/server/authority,761,80,0,260,1101,False,0.072661,MM,NaN,128.31.0.39:9131,2022-07-01,2023-06-19,NaT,NaT,NaN,MM_http://128.31.0.39:9131/tor/server/authority
1,http://131.188.40.189/tor/server/authority,1019,30,0,63,1112,False,0.026978,MM,NaN,131.188.40.189,2022-07-01,2023-06-19,NaT,NaT,NaN,MM_http://131.188.40.189/tor/server/authority
2,http://154.35.175.225/tor/server/authority,540,450,0,81,1071,False,0.420168,MM,NaN,154.35.175.225,2022-07-01,2023-06-19,NaT,NaT,NaN,MM_http://154.35.175.225/tor/server/authority
3,http://171.25.193.9:443/tor/server/authority,969,20,0,68,1057,False,0.018921,MM,NaN,171.25.193.9:443,2022-07-01,2023-06-19,NaT,NaT,NaN,MM_http://171.25.193.9:443/tor/server/authority
4,http://193.23.244.244/tor/server/authority,925,47,0,68,1040,False,0.045192,MM,NaN,193.23.244.244,2022-07-01,2023-06-19,NaT,NaT,NaN,MM_http://193.23.244.244/tor/server/authority
5,http://194.109.206.212/tor/server/authority,22,876,0,98,996,False,0.879518,MM,NaN,194.109.206.212,2022-07-01,2023-06-19,NaT,NaT,NaN,MM_http://194.109.206.212/tor/server/authority
6,http://199.58.81.140/tor/server/authority,980,34,0,70,1084,False,0.031365,MM,NaN,199.58.81.140,2022-07-01,2023-06-19,NaT,NaT,NaN,MM_http://199.58.81.140/tor/server/authority
7,http://204.13.164.118/tor/server/authority,991,32,0,63,1086,False,0.029466,MM,NaN,204.13.164.118,2022-07-01,2023-06-19,NaT,NaT,NaN,MM_http://204.13.164.118/tor/server/authority
8,http://66.111.2.131:9030/tor/server/authority,996,19,0,66,1081,False,0.017576,MM,NaN,66.111.2.131:9030,2022-07-01,2023-06-19,NaT,NaT,NaN,MM_http://66.111.2.131:9030/tor/server/authority
9,http://666games.net/,261,4,0,24,289,False,0.013841,MM,GAME,666games.net,2022-07-01,2023-06-30,NaT,NaT,NaN,MM_http://666games.net/
10,http://86.59.21.38/tor/server/authority,914,94,0,63,1071,False,0.087768,MM,NaN,86.59.21.38,2022-07-01,2023-06-19,NaT,NaT,NaN,MM_http://86.59.21.38/tor/server/authority
11,http://Facebook.com,0,0,0,2,2,False,0.000000,MM,NaN,Facebook.com,2023-06-03,2023-06-03,NaT,NaT,NaN,MM_http://Facebook.com
12,http://abc.go.com/,736,7,0,3,746,False,0.009383,MM,NEWS,abc.go.com,2022-07-01,2023-06-30,NaT,NaT,NaN,MM_http://abc.go.com/
13,http://abpr2.railfan.net/,388,8,0,88,484,False,0.016529,MM,MMED,abpr2.railfan.net,2022-07-02,2023-06-30,NaT,NaT,NaN,MM_http://abpr2.railfan.net/
14,http://absdfau.blogspot.com/,694,30,0,36,760,False,0.039474,MM,POLR,absdfau.blogspot.com,2022-07-01,2023-06-30,NaT,NaT,NaN,MM_http://absdfau.blogspot.com/
15,http://anonymizer.secuser.com/,823,16,0,42,881,False,0.018161,MM,ANON,anonymizer.secuser.com,2022-07-01,2023-06-30,NaT,NaT,NaN,MM_http://anonymizer.secuser.com/
16,http://anonymouse.org/,745,177,6,73,1001,True,0.182817,MM,ANON,anonymouse.org,2022-07-01,2023-06-30,2022-09-25,2023-05-14,133385,MM_http://anonymouse.org/
17,http://arakanhrdo.org/,629,341,0,63,1033,False,0.330106,MM,HUMR,arakanhrdo.org,2022-07-01,2023-06-30,NaT,NaT,NaN,MM_http://arakanhrdo.org/
18,http://atemmyanmar.org/,431,3,0,17,451,False,0.006652,MM,REL,atemmyanmar.org,2022-07-01,2023-06-29,NaT,NaT,NaN,MM_http://atemmyanmar.org/
19,http://atom.com.mm,0,1,0,0,1,False,1.000000,MM,NaN,atom.com.mm,2022-07-31,2022-07-31,NaT,NaT,NaN,MM_http://atom.com.mm

In [42]:
df_inputs_blocking_all.to_csv('inputs_all_list_2023_with_confirmed.csv')